name: Add/remove labels
description: Add/remove labels on an issue
inputs:
  add:
    description: label list (comma separated)
    required: false
  remove:
    description: label list (comma separated)
    required: false
  hyperjump_url:
    description: hyperjump webhook url
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
