# This action tests the "download-artifacts" action. Note that it runs on workflow_run events, so changes must
# be checked into the main branch before they can be tested.

name: "test-download-artifacts"

on:
  workflow_run:
    workflows: ["ci-test"]
    types:
      - completed

jobs:
  test-get-artifacts-single:
    runs-on: ubuntu-latest
    name: test get-artifacts from a single workflow run
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract single run's artifacts.
        uses: ./get-artifacts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifacts: test.download
          # the following two lines are default values included for clarity.
          target_dir: ./downloads/
          decompress: true
      - name: Test that "test.download" got downloaded
        run: |
          [[ -f  ./downloads/${{ github.event.workflow_run.id }}/artifacts/test.download/test-file.download ]]
          [ $( ls downloads/ | wc -l ) = 1 ]
      - name: Test that "test.not-download" did not get downloaded
        run: |
          [[ ! -f  ./downloads/${{ github.event.workflow_run.id }}/artifacts/test.not-download/test-file.not-download ]]

  test-get-artifacts-multiple:
    runs-on: ubuntu-latest
    name: test get-artifacts multiple workflow runs.
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract artifacts from the last ten runs of ci-test.yml on the master branch.
        uses: ./get-artifacts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file: ci-test.yml
          artifacts: test.download test.not-download
          # optional, otherwise all branches.
          branch: master
          # follow line is a default value included for clarity.
          history: 10
      - name: Test the last push to master resulted in artifacts
        run: |
          [[ -f ./downloads/${{ github.event.workflow_run.id }}/artifacts/test.download/test-file.download ]]
          [[ -f ./downloads/${{ github.event.workflow_run.id }}/artifacts/test.not-download/test-file.not-download ]]
        if: ${{ github.event.workflow_run.head_branch == 'master' }}
      - name: Test that multiple workflow run's files got downloaded
        run: |
          [ $( ls ${{ github.workspace }}/downloads/ | wc -l ) -gt 1 ]
