# This action tests the "download-artifacts" action. Note that it runs on workflow_run events, so changes must
# be checked into the main branch before they can be tested.

name: 'test-download-artifacts'

on:
  workflow_run:
    workflows: ["create-artifacts"]
    types:
      - completed

jobs:
  process-artifacts:
    runs-on: ubuntu-latest
    name: Process artifacts
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract artifacts
        uses: ./download-artifacts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          pattern: '^.*\.download$'
          extract: true
      - name: Test that "test.download" got downloaded
        run: |
          [[ -f artifacts/test.download.zip ]]
          cat artifacts/test.download/test-file.download
      - name: Test that "test.not-download" did not get downloaded
        run: |
          [[ ! -f artifacts/test.not-download.zip ]]
          [[ ! -f artifacts/test.not-download/test-file.not-download ]]
